############# English navigation ##############

# main menu
[[main]]
name = "Home"
pageRef = "/"
weight = 1

[[main]]
name = "Blog"
pageRef = "/blog"
weight = 2

[[main]]
name = "Resume"
url = "/files/resume.pdf"
weight = 3
